language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

addons:
  sonarcloud:
    organization: "bt-openlink"

git:
  depth: 99999

script:
  - ./gradlew sonarqube
  - ./gradlew bintrayUpload

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/   
